name: 'Create GitHub App Token'
description: 'Create a GitHub App installation token'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App private key'
    required: true
  installation-id:
    description: 'GitHub App installation ID'
    required: true
outputs:
  token:
    description: 'Generated installation token'
runs:
  using: 'node20'
  main: 'dist/index.js'
